[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040"
runner = "elf2uf2-rs"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
WIFI_NETWORK = "wifi-name"           # replace with your own value
WIFI_PASSWORD = "put-pw-here"        # same
